project.author=shanshi

# database connection setting
db.driver.name=com.mysql.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/shanshi_autojava?useUnicode=true&characterEncoding=utf8&useSSL=false
db.username=root
db.password=123456

# ????????
ignore.table.prefix=true

# add bean param suffix
bean.param.suffix=Query
bean.property.suffix.fuzzy=Fuzzy
bean.property.suffix.time.start=Start
bean.property.suffix.time.end=End

# mapper's suffix
mapper.suffix=Mapper

# project's base java directory
path.java=E:/project/shanshi-autojava-demo/src/main/java
path.resources=E:/project/shanshi-autojava-demo/src/main/resources
package.base=com.shanshi
package.entity.po=entity.po
package.entity.query=entity.query
package.utils=utils
package.enums=enums
package.mapper=mapper
package.service=service
package.exception=exception
package.controller=controller
package.service.impl=impl
package.entity.vo=entity.vo
package.entity.dto=entity.dto

# ignore property list
ignore.bean.tojson.field=id
ignore.bean.tojson.expression=@JsonIgnore
ignore.bean.tojson.class=import com.fasterxml.jackson.annotation.JsonIgnore

# date formation serialize
bean.date.serialize.expression=@JsonFormat(pattern = "%s", timezone = "GMT+8")
bean.date.serialize.class=import com.fasterxml.jackson.annotation.JsonFormat
# date formation deserialize
bean.date.deserialize.expression=@DateTimeFormat(pattern = "%s")
bean.date.deserialize.class=import org.springframework.format.annotation.DateTimeFormat





